---
- name: Install Docker on VM2, VM3, VM4, and VM5
  hosts: all
  become: true
  tasks:
  
    - name: Copy the script-docker.sh from VM2 to remote VM
      ansible.builtin.copy:
        src: ~/ansible/script-docker.sh
        dest: /tmp/script-docker.sh
        mode: '0755'

    - name: Run the script to install Docker
      ansible.builtin.shell: /tmp/script-docker.sh
      args:
        removes: /tmp/script-docker.sh
